Раздел 7. Задача 3. Карусель
js-tasks-ru/jsbasic-20220124_vita1980 pull request #12
Opened 2022-02-21 19:10 UTC by Vitalyanova

Слайдер работает, но не проходит 2 теста: кнопка вперед и кнопка назад, потому что не рассчитывается ширина элемента с классом .carousel__slide . Уже все перепробовала, не могу найти, почему ширина этого элемента не считается. При этом сами кнопки работают.

2022-02-21 19:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-22 19:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-23 11:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-23 11:56 UTC, Vitalyanova commented
@koalex, теперь у меня та же ситуация с Модальным окном, как и с каруселью. Модальное окно работает, но тесты не проходит.

2022-02-24 10:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-24 11:29 UTC, koalex requested changes
Отписал в SLACK что исправить

2022-02-24 18:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-25 19:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-28 14:34 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-28 15:54 UTC, koalex approved these changes

2022-02-28 15:55 UTC, merged